services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"
volumes:
  postgres_data: